// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import { Mulish, Roboto } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import AnimatedBackground from "@/components/AnimatedBackground";



const mulish = Mulish({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-mulish",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Kingsley Chukwubuike | Full Stack Developer",
 icons: {
    icon: [
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon.ico' }
    ],
    apple: '/apple-touch-icon.png'
  },
  description:
    "Portfolio of Kingsley Chukwubuike, a full-stack developer specializing in React, React Native, Next.js, Express, MySQL, MongoDb and Solidity.",
  keywords:
    "Kingsley, Chukwubuike, Adane Technology, Web Developer, Database, Web development, Web Design, Full Stack Developer, React, Next.js, Node.js, MySQL, Solidity, Figma",
  authors: [{ name: "Kingsley Chukwubuike" }],
  openGraph: {
    title: "Kingsley Chukwubuike | Full Stack Developer",
    description:
      "Building scalable E-commerce platforms, portfolio, co-operate websites, blogs, exchanges, mobile apps,  blockchain apps, and web systems globally.",
    url: "https://adane.vercel.app",
    type: "website",
    // images: [
    //   {
    //     url: "https://adane.vercel.app/preview.jpg",
    //     width: 1200,
    //     height: 630,
    //     alt: "Kingsley Chukwubuike Portfolio",
    //   },
    // ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Kingsley Chukwubuike | Full Stack Developer",
    description:
      "Explore the portfolio of Kingsley, a global full-stack developer and founder of Adane Technology.",
    creator: "@AdaneTech",
    // images: ["https://adane.vercel.app/preview.jpg"],
  },
  alternates: {
    canonical: "https://adane.vercel.app",
    languages: {
      "en": "https://adane.vercel.app/en",
      "en-US": "https://adane.vercel.app/en-us",
      "en-GB": "https://adane.vercel.app/en-gb",
      "fr": "https://adane.vercel.app/fr",
      "de": "https://adane.vercel.app/de",
      "es": "https://adane.vercel.app/es",
      "en-NG": "https://adane.vercel.app/ng",
      "x-default": "https://adane.vercel.app",
    },
  },
  other: {
    "application/ld+json": JSON.stringify({
      "@context": "https://schema.org",
      "@type": "Person",
      name: "Kingsley Chukwubuike",
      url: "https://adane.vercel.app",
      sameAs: [
        "https://github.com/buike369",
        "https://linkedin.com/in/kingsleychukwubuike",
      ],
      jobTitle: "Full Stack Developer",
      worksFor: {
        "@type": "Organization",
        name: "Adane Technology",
      },
    }),
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${mulish.variable} ${roboto.variable}`}>
      <body
      className={roboto.className}
      >
        <AnimatedBackground />
        {/* {children} */}
         <main className="relative z-10">{children}</main>
        </body>
    </html>
  );
}

